version: "3.1"

services:
  nginx:
    build: ./docker/nginx/
    container_name: web_container
    volumes:
      - .:/var/www/html
    depends_on:
      - php
    ports:
      - 80:80
    networks:
      - server
  php:
    build: ./docker/php/
    container_name: php
    expose:
      - 9000
    networks:
      - server
      - database
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    networks:
      - database
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: yii_docker
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
  adminer:
    image: clue/adminer
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - database

volumes:
  data:

networks:
  server:
  database:
